# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-02 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.CharField(default='none', max_length=1000),
            preserve_default=False,
        ),
    ]
