# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-03 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.CharField(max_length=1000000000000000000),
        ),
    ]
