# Generated by Django 2.1.5 on 2019-02-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20190203_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.FileField(default='books_pdf/None.pdf', upload_to='books_pdf/'),
        ),
    ]
